[package]
name = "chipa-ta-utils"
version = "0.1.0"
edition = "2024"

[features]
schemars = ["dep:schemars"]

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
thiserror = "2.0.12"
schemars = { version = "1.0.4", optional = true }
